# Generated by Django 5.2.6 on 2025-10-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('consultancy', 'Consultancy & Advisory Services'), ('counselling', 'Counselling & Psychotherapy Services'), ('training', 'Training & Capacity Building Services')], max_length=20),
        ),
    ]
