# Generated by Django 5.2.6 on 2025-10-19 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_servicebooking_email_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='features',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('consultancy', 'Consultancy and Advisory'), ('counselling', 'Counselling and Psychotherapy'), ('training', 'Training Programs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_type',
            field=models.CharField(choices=[('consultancy', 'Consultancy and Advisory'), ('counselling', 'Counselling and Psychotherapy'), ('training', 'Training Programs')], max_length=20),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='content.service')),
            ],
        ),
    ]
