# Generated by Django 5.2.6 on 2025-10-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_service_features_alter_service_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(help_text='Short description shown on blog cards')),
                ('content', models.TextField(help_text='Full blog content shown in modal')),
                ('image', models.ImageField(blank=True, help_text='Blog featured image', null=True, upload_to='blogs/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('consultancy', 'Consultancy and Advisory'), ('counselling', 'Counselling and Psychotherapy'), ('training', 'Training')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_type',
            field=models.CharField(choices=[('consultancy', 'Consultancy and Advisory'), ('counselling', 'Counselling and Psychotherapy'), ('training', 'Training')], max_length=20),
        ),
    ]
