# Generated by Django 5.2.6 on 2025-10-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_blog_alter_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='session_mode',
            field=models.CharField(choices=[('in-person', '🏢 In-Person'), ('online', '💻 Online'), ('telephone', '📞 Telephone')], default='in-person', max_length=20),
        ),
    ]
