# Generated by Django 5.2.6 on 2025-11-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_servicebooking_session_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
